/*
 * Copyright 2015 Ziou
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SINE_WAVE_CPP__SINE_WAVE_RECIEVER_HPP_
#define SINE_WAVE_CPP__SINE_WAVE_RECIEVER_HPP_

#include "sine_wave_cpp/srv/convert_image.hpp"

#include <rclcpp/rclcpp.hpp>

#include <sensor_msgs/msg/image.hpp>
#include <std_msgs/msg/float64.hpp>

#include <cv_bridge/cv_bridge.h>

// Include the generated parameter library header.
#include <sine_wave_cpp/sine_wave_parameters.hpp>

class SineWaveReciever
{
public:
  /**
   * @brief A SineWaveReciever object
   * @param node  Shared pointer of rclcpp::Node
   * @param params The sine wave's parameters generated by generate_parameter_library
   */
  SineWaveReciever(rclcpp::Node::SharedPtr node, const sine_wave::Params & params);

private:
  /**
   * @brief sine wave callback fuction to process the recieved sine wave
   * @param msg  sine wave msg
   */
  void sinewaveCallback(const std_msgs::msg::Float64::SharedPtr msg);

  /**
   * @brief image convert service
   * @param request the request of clinet is the raw image
   * @param response the response is a grayscale image
   */
  void convertImageService(
    const std::shared_ptr<sine_wave_cpp::srv::ConvertImage::Request> request,
    std::shared_ptr<sine_wave_cpp::srv::ConvertImage::Response> response);

  // declare node, subscription and service
  rclcpp::Node::SharedPtr node_;
  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr subscription_;
  rclcpp::Service<sine_wave_cpp::srv::ConvertImage>::SharedPtr service_;

  // Sine wave parameters
  double amplitude_;
  double angular_frequency_;
  double phase_;
  double frequency_;
};

#endif  // SINE_WAVE_CPP__SINE_WAVE_RECIEVER_HPP_
